## **Numpy**  

NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python".

In [ ]:
import numpy as np

arr = np.array([1,2,3,4])

print(arr)

print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
arr = np.array([1,2], [1,2])

print(arr)

TypeError: Field elements must be 2- or 3-tuples, got '1'

In [ ]:
arr = np.ones((3,5)) #display 3 row 5 columns

print(arr)

arr2 = np.zeros((4,6)) #display 4 row 6 columns

print(arr2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# **0-D Arrays**
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [ ]:
import numpy as np

arr0 = np.array(42)

print("Zero array: ", arr0)

Zero array:  42


In [ ]:
arr0 = np.array(22)

print(arr0)

22


# **1-D Arrays**
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# **2-D Arrays**
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr2= np.array([[2,3,4], [5,6,7]])

print(arr2)

[[2 3 4]
 [5 6 7]]


In [ ]:
arr2 = np.array([[2,3,4], [7,9,8]])

print(arr2)

[[2 3 4]
 [7 9 8]]


# **3-D arrays**
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
arr3 = np.array([[[2,3,4],[7,5,6]], [[5,5,4],[6,9,0]]])
print(arr3)

[[[2 3 4]
  [7 5 6]]

 [[5 5 4]
  [6 9 0]]]


In [ ]:
arrz = np.array([[[1,4,5], [6,5,4]] ,[[4,5,6], [5,9,8]]])

print("3-D Array: ", arrz)

3-D Array:  [[[1 4 5]
  [6 5 4]]

 [[4 5 6]
  [5 9 8]]]


In [ ]:
arrx= np.array([[[1,4,2,4],[3,6,7,8], [5,6,7,8], [7,8,9,2]]])
print(arrx)

[[[1 4 2 4]
  [3 6 7 8]
  [5 6 7 8]
  [7 8 9 2]]]


# **Check Number of Dimensions?**
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [ ]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
a = np.array(42)
b =np.array([1,2,3,4,5])
c = np.array([[1,2,3], [4,6,7]])
d = np.array([[[1,5,2], [4,5,6], [4,8,9], [9,5,2]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# **Higher Dimensional Arrays**
An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

Create an array with 5 dimensions and verify that it has 5 dimensions:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


# **Function**

In [ ]:
def function(b,h):
  area = b*h/0.25
  return area

function(2.66, 3.55)


37.772

In [ ]:
def num(a,b):
  z= a+b
  return z

num(3,7)

10

In [ ]:
def mu_function(a,b):
  x= a+b
  y= a-b
  z= a*b

  return x,y,z

mu_function(2,3)

(5, -1, 6)

In [ ]:
#user enter the two or more than value enter and than add the number subtract the num and mutiple the number
def my_func2(a,b):
  x= a+b
  y= a-b
  z= a*b
  return x,y,z

my_func2(int(input()), int(input()))




3
2


(5, 1, 6)

In [ ]:
#user enter the two or more than value enter and than add the number subtract the num and mutiple the number
def my_func2(*x):
  total_sum = sum(x)
  return total_sum

my_func2(int(input()), int(input()))

3
4


TypeError: 'int' object is not callable

In [ ]:
def calculate_operations():
    # Get user input
    numbers_input = input("Enter two or more numbers separated by spaces: ")

    # Convert input string into a list of numbers
    numbers = list(map(float, numbers_input.split()))

    # Check if user entered at least two numbers
    if len(numbers) < 2:
        print("Please enter at least two numbers.")
        return

    # Perform operations
    total_sum = sum(numbers)

    # Subtraction: start from the first number and subtract the rest
    total_subtract = numbers[0]
    for num in numbers[1:]:
        total_subtract -= num

    # Multiplication
    total_multiply = 1
    for num in numbers:
        total_multiply *= num

    # Print results
    print("Sum:", total_sum)
    print("Subtraction:", total_subtract)
    print("Multiplication:", total_multiply)

# Example usage
calculate_operations()


Enter two or more numbers separated by spaces: 3 5 6 
Sum: 14.0
Subtraction: -8.0
Multiplication: 90.0


In [ ]:
def my_func(b, c =3, d='HI'):
  return b+c

my_func(5,3,'Hello')
my_func(5,3)
my_func(5)

8

In [ ]:
def Number(a,b):
  return a +b, a-b, a*b

total_sum, prod, diff = Number(10,4)
print(total_sum)

result = Number(10,3)
print(result)
print(result[0])

14
(13, 7, 30)
13


In [ ]:
def math_operator(a,b):
  return a +b , a *b, a-b

sum, prod, diff = math_operator(10,4)
print(sum)

result = math_operator(10,3)
print(result)
print(result[0])

print(sum, prod, diff)

result = math_operator(10,3)
print(result)
print(result[0])
result[0]= 50

#

14
(13, 30, 7)
13
14 40 6
(13, 30, 7)
13


TypeError: 'tuple' object does not support item assignment

In [ ]:
def change_list(my_list):
  my_list.append([1,2,3,4])
  print("Inside the function: ", my_list)
  return

my_list = [10,20,30]
print("Before the function call: ", my_list)
change_list(my_list)
print("After the function call: ", my_list)


Before the function call:  [10, 20, 30]
Inside the function:  [10, 20, 30, [1, 2, 3, 4]]
After the function call:  [10, 20, 30, [1, 2, 3, 4]]


In [ ]:
def new_function(x=1 , y =2, z =3):
  return (2*x , 4*y, 8*z)
new_function()

(2, 8, 24)

In [ ]:
def add(x,y,z):
  return (2*x, 4*y, 8*z)

add(4,12,32)

(8, 48, 256)

In [ ]:
def new_fun(x,y,z):
  return (2*x, y*3, z*4)

new_fun(4, y=6, z=2)

(8, 18, 8)

In [ ]:
def new_add(x=1, y=2, z=3):
  return (2*x, y*3, z*4)
new_add(2, y=4, z=9)
#new_add(y=6, z=2, 9)

(4, 12, 36)

Argument to function

return value if function

Assigned to variable

part od tuple list

In [ ]:
def square(x):
  return x*x

def appiler(q,x):
  return q(x)

appiler(square,5)


25

*x ka matlab hai:

→ Function kisi bhi number of arguments ko accept kar sakta hai (1, 2, 3 ya jitnay marzi).

x ke andar tuple ban jata hai, jismein saari values store hoti hain.

print(x) → Wo tuple ko print kar raha hai (jo values aap function ko dete hain).



In [ ]:
def varpafu(*x):
  print(x)
varpafu()

()


In [ ]:
def add(*num):
  sum =0

  for n in num:
    sum = sum + n

  print("Sum:",sum)

add(3,5)
add(4,5,6,7)
add(1,2,3,5,6)

Sum: 8
Sum: 22
Sum: 17
